name: Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    
    permissions:
      checks: write
    
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.7+7'
          distribution: 'liberica'
          java-package: 'jdk+fx'

      - name: Cache local Maven repository and JDK cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            target/jdkCache
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: ./mvnw test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      - name: JaCoCo Code Coverage Report
        id: jacoco_report
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false # set to true for Github CI build failing when coverage check do not pass
          publish_only_summary: false
